### ISSUE TITLE
Example and blog post are fantastic!

### ISSUE THREAD

**Issue by stacktracer** [antonmata/Web-Workers-With-Visual-Studio-Code-s-Intellisense#1]
(Not actually an issue, but this seems to be the easiest way to leave a comment ... I always have problems signing into Disqus.)

This is fantastic. Thank you for both the example code skeleton and the blog post! They are exactly what I was looking for. There are a couple of other approaches floating around on the web, but nothing that shows how to use a different tsconfig for the worker. I was just about the give up on Webpack and write a shell script!

**Comment by atamocius** [comment]
You are very welcome sir! I am glad that it helped you out. This repo and that post were created specifically to *pay it forward*.

Also, the act of having different tsconfigs for different folders is supported by default by TypeScript, but it seemed so rare in a lot of examples/tutorials out there. It was just so frustrating that something that was supported by default seemed so esoteric in practice.
